### ISSUE TITLE
VerifyError crash at app start

### ISSUE THREAD

**Issue by sunxu3074** [getsentry/sentry-android-gradle-plugin#734] opened 2024-07-17 09:49 UTC
### Gradle Version

8.4

### AGP Version

8.3.1

### Code Minifier/Optimizer

R8

### Version

4.10.0

### Sentry SDK Version

7.12.0

### Steps to Reproduce

1. sentry config : 
    ```groovy
    sentry {
      debug = true
      projectName = "xxx"
      org = "xxx"
      authToken = "xxx"
      autoUploadProguardMapping = true
      autoUploadNativeSymbols = true
      includeProguardMapping = true
      includeSourceContext = true
      tracingInstrumentation {
          enabled = true
          logcat {
              enabled = true
              minLevel = LogcatLevel.DEBUG
          }
    }
   ```
2. I have integrated a third-party advertising SDK.
3. When I run the application with the above configuration in the release environment, it crashes immediately. 

### Expected Result

How should I solve this problem? Is it related to me enabling the tracingInstrumentation configuration? To be honest, I don't really want to turn off this configuration.

### Actual Result

```
java.lang.VerifyError: Verifier rejected class com.inno.innosdk.utils.AppInfomation: 
	java.lang.Boolean com.inno.innosdk.utils.AppInfomation.e() failed to verify: java.lang.Boolean com.inno.innosdk.utils.AppInfomation.e(): [0x35] register v5 has type Precise Reference: byte[] but expected Reference: java.io.FileInputStream
    	int com.inno.innosdk.utils.AppInfomation.n() failed to verify: int com.inno.innosdk.utils.AppInfomation.n(): [0x34] register v6 has type Precise Reference: byte[] but expected Reference: java.io.FileInputStream (declaration of 'com.inno.innosdk.utils.AppInfomation' appears in /data/app/~~-CjjARYXtcgYkgnTSiIImQ==/com.example-QXTHqt58-7zvhf_VhvLp8w==/base.apk!classes4.dex)
	    	at com.inno.innosdk.pb.InnoMain.loadInfo(SourceFile:28)
	    	at com.qumeng.advlib.__remote__.core.proto.request.Device.initTkidTuid(Device.java:226)
	    	at com.qumeng.advlib.__remote__.core.b.a(ICliFactoryProxy.java:199)
	    	at com.qumeng.advlib.__remote__.core.ICliFactory.<init>(ICliFactory.java:110)
	    	at java.lang.reflect.Constructor.newInstance0(Native Method)
	    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	    	at com.qumeng.advlib.common.b.a(SourceFile:4)
	    	at com.qumeng.advlib.common.b.a(SourceFile:3)
	    	at com.qumeng.advlib.core.a.b(Unknown Source:16)
	    	at com.qumeng.advlib.core.a.c(Unknown Source:24)
	    	at com.qumeng.advlib.core.a.<init>(Unknown Source:14)
	    	at com.qumeng.advlib.core.a.a(SourceFile:1)
	    	at com.qumeng.advlib.api.AiClkAdManager.init(SourceFile:2)
	    	at com.qumeng.advlib.gm.QMCustomerConfig$1.run(Unknown Source:24)
	    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	    	at java.lang.Thread.run(Thread.java:1042)
```

**Comment by sunxu3074** [comment] 2024-07-17 10:06
when i use like : 
```groovy
tracingInstrumentation {
        enabled = true
        appStart {
            enabled = false
        }
}        
```
It still crashes. It only doesn't crash when I disable tracingInstrumentation.

**Comment by markushi** [comment] 2024-07-17 10:41
Hi @sunxu3074 thanks for reaching out!
We've encounter a similar issue in the past, where obfuscated third party SDKs are causing issues with our instrumentation.

Could you try the following?
```gradle
sentry {
    tracingInstrumentation {
        excludes.set(setOf("com/inno/innosdk/**"))
    }
}
```

If the above doesn't work, you could also try and disable all instrumentation features:
```gradle
tracingInstrumentation {
        enabled = false
}
```

**Comment by sunxu3074** [comment] 2024-07-17 11:23
Thank you very much, the excludes worked.

**Comment by markushi** [comment] 2024-07-17 12:47
Linking https://github.com/getsentry/sentry-android-gradle-plugin/issues/714 here too, as this is a dup. And closing it as well since the issue is resolved, thanks for the speedy response!

**Closed by markushi** 2024-07-17 12:47 UTC
Labels: bug, Platform: Android, Waiting for: Product Owner
