### ISSUE TITLE
Race condition when creating and packaging sentry-debug-meta.properties

### ISSUE THREAD

**Issue by headsvk** [getsentry/sentry-android-gradle-plugin#37] opened 2020-11-10 22:47 UTC
_Android Gradle Plugin:_
**4.1.0**

_Gradle:_
**6.7**

_Optimizer:_
- [X]  R8

_Have you created the sentry.properties file?_
- [X]  Yes -> in project root

_SDKs:_
- [X]  sentry-android -> 3.1.3

---
I have the following issue:

Android crash reports are not deobfuscated on Sentry.io.
App log shows:
> I/Sentry: sentry-debug-meta.properties file was not found.

On clean build, the file is correctly created in `build/intermediates/merged_assets` folder but it's missing from the final apk.
On rebuild, the file is included in the apk.

**Steps to reproduce:**
- Run `gradlew clean assembleRelease` and open the final apk

**Actual result:**
- `sentry-debug-meta.properties` doesn't get packaged into apk's assets folder

**Expected result:**
- `sentry-debug-meta.properties` gets packaged into apk's assets folder

**Comment by mrrobot97** [comment] 2020-11-11 02:29
I'm also seeing this issue, any workaround?

**Comment by mrrobot97** [comment] 2020-11-11 02:45
I'm having exactly the same issue, if you execute clean task before assembleRelease, the sentry-debug file won't be packaged into the apk, but if you rebuild without a clean task, the sentry-debug file will be packaged into the apk.

AGP version: 4.1.0
gradle version:6.5
sentry-android-gradle-plugin version:1.7.36
sentry-android sdk version:3.1.1

**Comment by marandaneto** [comment] 2020-11-11 08:42
that's odd, but I can't reproduce it, already tried a few times, could any of you make a sample case? this could be either because of a combination of Gradle and AGP version or even how the app modules are structured within the project, so a sample case would be helpful, thanks.

**Comment by mrrobot97** [comment] 2020-11-11 09:25
@marandaneto I upload a demo project and I can reproduce the problem with this empty project. I'm using Android Studio 4.1 btw. Here's the repo: https://github.com/mrrobot97/SentryGradlePluginIssueDemo

**Comment by marandaneto** [comment] 2020-11-11 11:55
I can confirm also using AGP 4.1.1 and Gradle 6.7, `clean assembleRelease` doesn't work sometimes, but running `assembleRelease` again just works, looking into it

**Comment by headsvk** [comment] 2020-11-11 12:59
@mrrobot97 great that you could make a repo so quickly!
I want to add I thought it might be a filesystem issue but it happens on my Windows PC and Linux CI

**Comment by marandaneto** [comment] 2020-11-11 13:32
For a quick update, I can't reproduce the issue if using Gradle <= 6.4.x and AGP <= 4.0.x, so a workaround, for now, would be to downgrade them, still looking into it.

**Comment by marandaneto** [comment] 2020-11-11 13:54
yeah but it's not only about AGP I'd say, Gradle 6.7 and AGP 4.0.x still causes the issue, I need to read their changelogs now and see if I can find out.

**Comment by marandaneto** [comment] 2020-11-11 16:46
I debugged a bit more and found out the following case on the 2nd run (without the `clean`):

Task ':app:packageRelease' is not up-to-date because:
  Input property 'assets' file /Users/marandaneto/Github/SentryGradlePluginIssueDemo/app/build/intermediates/merged_assets/release/out/sentry-debug-meta.properties has been added.

so we need to execute our task after `minifyReleaseWithR8` and before `packageRelease`, so we have the time to generate the file and to be packaged in the final apk, and this is being done at the right time, I can check the timeline on build `scan`.

the thing is, looks like Gradle keeps a caching of the files in memory and it's not somehow notified that a new file has been created and in the 2nd run, it identifies a new file (see debug message above) and pack it, I'm still not sure how to solve that, looks like the code is correct but Gradle is not up to date if we write a file on the folder at the last minute.
I'll need to learn a bit more of the internals of Gradle and AGP.

**Comment by marandaneto** [comment] 2020-11-12 09:18
I've opened a regression issue on Gradle's repo, sorry about that, looks like a regression on Gradle or AGP rather than a bug on the plugin, unless this is related to the new incremental and caching system which we don't take advantage of it, if it's the case, we'd prioritize to rewrite this plugin as it's on our backlog anyway.

**Comment by Whathecode** [comment] 2021-01-04 17:25
I [ran into the same problem](https://forum.sentry.io/t/android-debug-files-correctly-uploaded-but-issues-do-not-show-symbolicated-view/12303/7) using AGP 7.0.0-alpha.03 and Gradle 6.8-rc1.

Running `assembleRelease` twice is a workaround for now.

**Comment by clembou** [comment] 2021-01-19 10:33
Hi all, I previously hit a very similar issue on a previous version of the plugin, and at the time as a temporary workaround I received the suggestion to force the metadata file generation as described here: https://github.com/getsentry/sentry-java/issues/740#issuecomment-516885006

Unfortunately no such luck this time, as mentioned above the ordering itself appears to be fine. In our case running the build twice is quite onerous as a workaround, so we will probably roll back for now, if anyone find a way to trick gradle into picking up the `merged_assets` file before packaging please shout!  I have a feeling there should be a way to add a custom gradle task copying the file, but this is beyond my gradle skills.

**Comment by ansman** [comment] 2021-02-12 14:47
Did you consider allowing passing the mapping file ID when uploading them instead of relying on the backend to generate one? This would allow you to work around this issue since you can generate the build ID much earlier in the process.

**Comment by ansman** [comment] 2021-02-12 23:27
As it turns out the CLI already supports passing the UUID. I've fixed this issue in #41 using the method and I've verified it in our project.

**Comment by marandaneto** [comment] 2021-03-09 12:16
@headsvk we're currently rewriting the Gradle Plugin and this will solve the issue, using also @ansman fixes but not only.
Subscribe to #50 :)

**Comment by marandaneto** [comment] 2021-04-30 08:10
this issue should be solved by https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/2.0.0-alpha.3
please report any issues you may find, thanks for the patience

**Closed by marandaneto** 2021-04-30 08:10 UTC
Labels: bug
