### ISSUE TITLE
Error logs about missing cli auth token after updated to 4.5

### ISSUE THREAD

**Issue by G00fY2** [getsentry/sentry-android-gradle-plugin#697] opened 2024-04-25 14:35 UTC
### Gradle Version

8.7

### AGP Version

8.3.2

### Code Minifier/Optimizer

None

### Version

4.5

### Sentry SDK Version

7.8.0

### Steps to Reproduce

- Add Sentry Android Gradle plugin to project
- Configure the sentry plugin with `ignoredBuildTypes.set(setOf("debug"))`
- Do not install or setup the Sentry CLI
- run assembleDebug to build an Android project

### Expected Result

Since the build type is ignored no sentry CLI task is executed and no Sentry errors are logged

### Actual Result

We always see an Gradle error log with (the build luckily still succeeds)

> Auth token is required for this request. Please run `sentry-cli login` and try again!

**Comment by LionZXY** [comment] 2024-04-29 15:24
Has anyone come up with a workaround for this yet?

**Comment by markushi** [comment] 2024-04-29 16:39
Hi everyone, thanks for reaching out!
I just tried to reproduce(same Gradle, AGP and sentry Gradle plugin versions) this quickly, but unfortunately couldn't.

Could you share a few more details about your setup?
1. A snippet of your `sentry { }` `.gradle` config
2. Are you using the new EU region?

Additionally our telemetry could be the root cause, as it utilizes sentry-cli under the hood. You can disable it via the configuration block and try if it works then.
```kotlin
sentry {
    telemetry.set(false)
}
```

Additionally you can enable debugging an run your gradle task with the `--info` flags to get more details about the tasks being executed.

```kotlin
sentry {
    debug.set(true)
}
```

**Comment by LionZXY** [comment] 2024-04-30 00:24
`telemetry.set(false)` does not work : (
That's a reproducible example log:
https://github.com/flipperdevices/Flipper-Android-App/actions/runs/8887106408/job/24401803084?pr=840#step:4:11306
[This branch](https://github.com/flipperdevices/Flipper-Android-App/tree/debug/sentry) with the command `./gradlew assembleInternal`.

**Comment by G00fY2** [comment] 2024-04-30 07:06
Actually the error log is gone after configuring `telemetry.set(false)`! Maybe it makes sense to only try sending telemetry if the auth token is available?

For me it seems like this was executed while configuration phase. Because the error message was always very early in the logs, right after the Android variants got configured.

@LionZXY Maybe you have `autoUploadProguardMapping` enabled locally? We currently configured it like this `autoUploadProguardMapping.set(isCI)`.

**Comment by markushi** [comment] 2024-04-30 08:30
Thanks for all the details, I can finally reproduce the issue. It looks like a recent `sentry-cli` version bump is the underlying issue, as it seems to ignore the `--no-upload` argument, causing requests to be made when they shouldn't. We're on it!

**Comment by markushi** [comment] 2024-05-01 06:26
Quick update: We shipped a bugfix with our `4.5.1` release. Please give it a try and let us know if the issue is resolved for you as well.

**Comment by markushi** [comment] 2024-05-08 13:09
Re-opening this issue as we see error logs in the gradle build which are causing some confusion (Note: the build still succeeds).

**Comment by tjohnn** [comment] 2024-05-08 17:29
@markushi I was also getting the same issue on 4.5.1 but it got resolved by disabling telemetry.

**Comment by bfricka** [comment] 2024-05-08 19:01
> @markushi I was also getting the same issue on 4.5.1 but it got resolved by disabling telemetry.

Same.

**Comment by sebokopter** [comment] 2024-05-13 17:00
Same here with 4.5.1. According to the Gradle debug logs calling `sentry-cli info` already warns about the missing auth token:

```
2024-05-13T18:46:07.022+0200 [INFO] [org.gradle.process.internal.DefaultExecHandle] Starting process 'command '/Users/dev/android/app/build/tmp/sentry-cli-2.31.1.exe''. Working directory: /Users/dev/android Command: /Users/dev/android/app/build/tmp/sentry-cli-2.31.1.exe --log-level=error info
2024-05-13T18:46:07.022+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
2024-05-13T18:46:07.022+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command '/Users/dev/android/app/build/tmp/sentry-cli-2.31.1.exe'.
2024-05-13T18:46:07.025+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
2024-05-13T18:46:07.026+0200 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
2024-05-13T18:46:07.026+0200 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command '/Users/dev/android/app/build/tmp/sentry-cli-2.31.1.exe''
2024-05-13T18:46:07.038+0200 [ERROR] [system.err] error: Auth token is required for this request. Please run `sentry-cli login` and try again!
2024-05-13T18:46:07.038+0200 [ERROR] [system.err]
2024-05-13T18:46:07.038+0200 [ERROR] [system.err] Add --log-level=[info|debug] or export SENTRY_LOG_LEVEL=[info|debug] to see more output.
2024-05-13T18:46:07.038+0200 [ERROR] [system.err] Please attach the full debug log to all bug reports.
2024-05-13T18:46:07.038+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
2024-05-13T18:46:07.038+0200 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command '/Users/dev/android/app/build/tmp/sentry-cli-2.31.1.exe'' finished with exit value 1 (state: FAILED)
```

**Comment by romtsn** [comment] 2024-05-16 08:27
I believe this should be tackled by #708 now

**Closed by romtsn** 2024-05-16 08:27 UTC
Labels: bug, Platform: Android, Waiting for: Product Owner

**Comment by romtsn** [comment] 2024-05-16 09:29
hey everyone here, the issue has been addressed in the version 4.6.0, which just has been published. Please give it a try and let us know. Thank you!

**Comment by KhaldiAmer** [comment] 2024-12-30 20:10
Just got this issue with version `6.4.0` @romtsn

**Comment by PlaneInABottle** [comment] 2025-01-20 21:07
My expo build fails because of this error on version `6.3.0`
