### ISSUE TITLE
Gradle plugin should be independent of CLI and SDK version

### ISSUE THREAD

**Issue by pvdmde** [getsentry/sentry-android-gradle-plugin#709] opened 2024-05-16 11:31 UTC
### Problem Statement

Users of the plugin should be able to update it without updating the other components.
Is there a technical reason why newest versions are forced?

**Comment by romtsn** [comment] 2024-05-16 14:42
hey, we simply bump the versions because we've tested their compatibility with the new gradle plugin version. You're actually not forced in any way, you can always override both the SDK and the CLI versions:

```kotlin
// SDK version
sentry {
  autoInstallation.sentryVersion.set("7.0.0")
}

// CLI version in your sentry.properties file
defaults.org=...
defaults.project=...
cli.executable=path/to/your/sentrycli
```

does that help?

**Comment by markushi** [comment] 2024-05-29 12:58
@pvdmde did you have any time to look into the answer above?

**Comment by pvdmde** [comment] 2024-05-29 15:56
I wrote a Story to try the autoInstallation and see if it works as expected. Might take a while.

I still think a tool should not depend on the newest version of its dependency without any good reason, but rather document its compatibility matrix.

Let the consumers control the version with their tools (Gradle) instead of a custom DSL.

Does the plugin actually need Sentry to do it's job? It feels not right actually.

**Comment by romtsn** [comment] 2024-05-29 17:35
no, it's a feature, that you can just disable if you don't see fit for your usecase and control the SDK dependency version yourself:

```gradle
sentry {
  autoInstallation.enabled.set(false)
}

dependencies {
  implementation("io.sentry:sentry-android:7.0.0") // <-- this won't get overwritten now
}
```

**Comment by romtsn** [comment] 2024-06-05 13:03
@pvdmde we're gonna close this issue, because, as I mentioned, you can disable the feature, and it's optional - noone is enforcing you to use a specific version of the SDK. Feel free to comment here or open a new issue if you encounter other problems. Thank you!

**Closed by romtsn** 2024-06-05 13:03 UTC
Labels: enhancement, Platform: Android, Waiting for: Community

**Comment by pvdmde** [comment] 2024-07-16 08:59
I'm not getting the result I expected.

I added autoInstallation.enabled.set(false) and kept the plugin the same, which yielded in the same sentry dependency we had before.

Then I increased the Plugin from 4.3.0 to 4.10.0 and the sentry dependency in the project got increased from 7.5.0 to 7.12.

We don't use sentry directly but via React Native, and there we pull in sentry-rn as 5.20 which has **api 'io.sentry:sentry-android:7.5.0'**

It is really a bad practice what Sentry is doing with its dependencies, needing to opt out from "autoinstall" which no other library is doing (for a good reason).

I will see if we can remove Sentry and use something else, it's just too much of a hassle to be honest.

**Comment by romtsn** [comment] 2024-07-16 09:42
@pvdmde thanks for your feedback. First off, I'm sorry you're having troubles and understand your frustration.

> Then I increased the Plugin from 4.3.0 to 4.10.0 and the sentry dependency in the project got increased from 7.5.0 to 7.12.

If that's the case when `autoInstallation.enabled.set(false)` is set, then this is not intended and is a bug. Or there's some other dependency that brings in `7.12.0` transitively. I've tried reproducing it locally, but wasn't able to, so if you can provide a reproducible sample, that'd be much appreciated!

> It is really a bad practice what Sentry is doing with its dependencies, needing to opt out from "autoinstall" which no other library is doing (for a good reason).

I agree that may be not transparent, but so far, we haven't received much negative feedback about the feature. In fact, this is the second or third time we receive such feedback, so I hope this feature is positively received most of the time. The reason it is enabled by default, is because we have many integrations that our customers might not be aware of, and we're trying to provide as much value out of the box as possible. If it was disabled by default, I doubt anyone would ever enabled it, simply because of not enough awareness. I hope that makes sense!

If there's anything we can do to make you reconsider looking for alternatives, I'm all ears. As mention, disabling auto-installation should eliminate all of your problems, and if it doesn't, it's most likely a bug.
