### ISSUE TITLE
SentryUploadNativeSymbolsTask is not configuration cache ready

### ISSUE THREAD

**Issue by cyrilmottier** [getsentry/sentry-android-gradle-plugin#730] opened 2024-07-10 13:49 UTC
### Gradle Version

8.8

### AGP Version

8.5.0

### Code Minifier/Optimizer

R8

### Version

4.5.1

### Sentry SDK Version

7.6.0

### Steps to Reproduce

Run `:app:uploadSentryNativeSymbolsForRelease`

### Expected Result

I would expect this not to display any error or warning but it triggers

```
Task `:apps:capture:uploadSentryNativeSymbolsForRelease` of type `io.sentry.android.gradle.tasks.SentryUploadNativeSymbolsTask`: invocation of 'Task.project' at execution time is unsupported.
See https://docs.gradle.org/8.8/userguide/configuration_cache.html#config_cache:requirements:use_project_during_execution
```

### Actual Result

If you look at the source code, the task is indeed reading `Task.project` [here](https://github.com/getsentry/sentry-android-gradle-plugin/blob/main/plugin-build/src/main/kotlin/io/sentry/android/gradle/tasks/SentryUploadNativeSymbolsTask.kt#L49C17-L49C24)

**Comment by romtsn** [comment] 2024-07-11 08:33
hi @cyrilmottier, thanks for reporting this, this indeed looks like an oversight from our side, we'll get this fixed with the next version and keep you posted!

**Comment by cyrilmottier** [comment] 2024-07-11 12:21
I don't get why but it looks it was already fixed several years ago by a friend of mine https://github.com/getsentry/sentry-android-gradle-plugin/pull/166. What happened?

**Comment by romtsn** [comment] 2024-07-11 12:33
looks like we've reverted it in an attempt to fix https://github.com/getsentry/sentry-android-gradle-plugin/issues/445, but apparently this wasn't the right thing to do. We'll look into other ways and add a test to ensure there's no regressions in the future.

**Closed** 2024-08-05 09:50 UTC
Labels: bug, Platform: Android

**Comment by romtsn** [comment] 2024-08-07 11:13
hey @cyrilmottier apologies for the delays, you can try version [4.11.0](https://github.com/getsentry/sentry-android-gradle-plugin/releases/tag/4.11.0) out and let us know if there are still issues with the task. Thanks!
