### ISSUE TITLE
Configuration cache issue with sentry-cli executable.

### ISSUE THREAD

**Issue by prashanOS** [getsentry/sentry-android-gradle-plugin#381] opened 2022-09-29 18:49 UTC
### Integration

sentry-android

### Build System

Gradle

### AGP Version

7.3.0

### Proguard

Enabled

### Version

6.4.2

### Steps to Reproduce

Occasionally when running a build with Proguard/R8 enabled and Gradle's configuration cache turned on, I'll run into this issue:

```
Execution failed for task ':app:uploadSentryProguardMappingsInternal'.
> A problem occurred starting process 'command '/var/folders/3z/jtlq288544zdqjdmlvsc3qmh0000gn/T/.sentry-cli7063660718712881532.exe''
    Cause: error=2, No such file or directory
```

Clearing Gradle's configuration cache (`rm -rf .gradle/configuration-cache`) fixes this issue. It seems that the Sentry Gradle tasks are not properly configured for use with configuration cache?

### Expected Result

Build succeeds successfully.

### Actual Result

```
Execution failed for task ':app:uploadSentryProguardMappingsInternal'.
> A problem occurred starting process 'command '/var/folders/3z/jtlq288544zdqjdmlvsc3qmh0000gn/T/.sentry-cli7063660718712881532.exe''
    Cause: error=2, No such file or directory
```

**Comment by romtsn** [comment] 2022-09-29 20:55
hey, thanks for report, this looks like a bug indeed, we've never tested with config cache. We'll take a look soon!

**Comment by romtsn** [comment] 2022-10-19 20:53
@prashanOS would you be able to provide a reproducible sample? I've tried to reproduce it locally with our sample projects, but no luck. I have some ideas on how this could be fixed, but ideally would need a reproducer to confirm on. Thanks in advance

**Comment by romtsn** [comment] 2022-11-04 08:11
@prashanOS were you able to consistently reproduce it? Otherwise we might need to close it as not reproducible

**Comment by romtsn** [comment] 2022-11-10 08:32
Closing as not reproducible, feel free to reopen with more details

**Closed by romtsn** 2022-11-10 08:32 UTC
Labels: bug, Impact: Medium, Platform: Android, waiting for feedback
